name: 'Manual Deploy'

on:
  workflow_dispatch:
    inputs:
      environment_name:
        required: true
        type: string
        default: uat
      terraform_apply:
        required: true
        type: string
        default: false
      recruit_version:
        required: true
        type: string
        
jobs: 
  run:
    name: Deploy to "${{ inputs.environment_name }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to "${{ github.event.inputs.environment_name }}""
      - run: echo "Deploy to "${{ github.event.inputs.terraform_apply == 'true' }}""
      - run: echo "Deploy to "${{ github.event.inputs.recruit_version }}""
